import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const packageRoot = path.join(here, "node_modules/lucide-static");
const manifest = JSON.parse(fs.readFileSync(path.join(packageRoot, "package.json"), "utf8"));
const nodes = JSON.parse(fs.readFileSync(path.join(packageRoot, "icon-nodes.json"), "utf8"));
const tags = JSON.parse(fs.readFileSync(path.join(packageRoot, "tags.json"), "utf8"));
const keys = Object.keys(nodes).sort((a, b) => a.localeCompare(b));

const escapeXml = value => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("\"", "&quot;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;");

const symbols = keys.map(key => {
  const children = nodes[key].map(([tag, attrs]) => {
    const attributes = Object.entries(attrs)
      .map(([name, value]) => `${name}=\"${escapeXml(value)}\"`)
      .join(" ");
    return `<${tag}${attributes ? ` ${attributes}` : ""}/>`;
  }).join("");
  return `<symbol id=\"${key}\" viewBox=\"0 0 24 24\">${children}</symbol>`;
});

const publicDir = path.join(root, "Vitorize.Web/wwwroot/lib/lucide");
fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(
  path.join(publicDir, "lucide-sprite.svg"),
  `<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\">${symbols.join("")}</svg>\n`,
  "utf8");
fs.copyFileSync(path.join(packageRoot, "LICENSE"), path.join(publicDir, "LICENSE"));
fs.writeFileSync(path.join(publicDir, "VERSION"), `${manifest.version}\n`, "utf8");

const csharp = value => String(value).replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
const rows = keys.map(key => {
  const searchTags = Array.isArray(tags[key]) ? tags[key].join(" ") : "";
  return `        (\"${csharp(key)}\", \"${csharp(searchTags)}\"),`;
});
const generated = `// <auto-generated />\nnamespace Vitorize.Shared.Icons;\n\ninternal static class LucideIconCatalogData\n{\n    internal const string PackageName = \"lucide-static\";\n    internal const string Version = \"${csharp(manifest.version)}\";\n    internal static readonly (string Key, string Tags)[] Items =\n    [\n${rows.join("\n")}\n    ];\n}\n`;
const sharedDir = path.join(root, "Vitorize.Shared/Icons");
fs.mkdirSync(sharedDir, { recursive: true });
fs.writeFileSync(path.join(sharedDir, "LucideIconCatalog.Generated.cs"), generated, "utf8");

console.log(`Generated ${keys.length} Lucide ${manifest.version} icons.`);
