// <auto-generated />
namespace Vitorize.Shared.Icons;

internal static class IconCatalogPhData
{
    internal const string Prefix = "ph";
    internal const string Title = "Phosphor";
    internal const string PersianTitle = "فسفر";
    internal static readonly (string Name, string Keywords)[] Items =
    [
        ("game-controller-fill", "game controller fill"),
        ("sword-fill", "sword fill"),
        ("shield-fill", "shield fill"),
        ("crown-fill", "crown fill"),
        ("trophy-fill", "trophy fill"),
        ("coin-fill", "coin fill"),
        ("wallet-fill", "wallet fill"),
        ("credit-card-fill", "credit card fill"),
        ("storefront-fill", "storefront fill"),
        ("package-fill", "package fill"),
        ("gift-fill", "gift fill"),
        ("ticket-fill", "ticket fill"),
        ("headset-fill", "headset fill"),
        ("chat-circle-fill", "chat circle fill"),
        ("bell-fill", "bell fill"),
        ("rocket-fill", "rocket fill"),
        ("lightning-fill", "lightning fill"),
        ("star-fill", "star fill"),
        ("heart-fill", "heart fill"),
        ("fire-fill", "fire fill"),
        ("medal-fill", "medal fill"),
        ("cube-fill", "cube fill"),
        ("gauge-fill", "gauge fill"),
        ("lock-key-fill", "lock key fill"),
        ("user-circle-fill", "user circle fill"),
        ("shopping-cart-fill", "shopping cart fill"),
        ("tag-fill", "tag fill"),
        ("percent-fill", "percent fill"),
        ("diamond-fill", "diamond fill"),
        ("crown-simple-fill", "crown simple fill")
    ];
}
