[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][ValidateNotNullOrEmpty()][string] $ServerInstance,
    [Parameter(Mandatory = $true)][ValidateSet('Development', 'Staging')][string] $Environment,
    [string] $DatabasePrefix = 'Vitorize_Rehearsal',
    [switch] $KeepDatabase,
    [string] $LogDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($DatabasePrefix -notmatch '^[A-Za-z][A-Za-z0-9_]{0,79}$') { throw 'DatabasePrefix must be an SQL-safe identifier.' }
$database = '{0}_{1}' -f $DatabasePrefix, ([Guid]::NewGuid().ToString('N'))
$database = $database.Substring(0, [Math]::Min($database.Length, 120))
$root = Split-Path -Parent $PSScriptRoot

try {
    & (Join-Path $PSScriptRoot 'Publish-CleanDatabase.ps1') -ServerInstance $ServerInstance -Database $database -Environment $Environment -ConfirmDatabaseName $database -LogDirectory $LogDirectory
    & (Join-Path $PSScriptRoot 'Upgrade-ExistingDatabase.ps1') -ServerInstance $ServerInstance -Database $database -Environment $Environment -Apply -ConfirmDatabaseName $database -LogDirectory $LogDirectory
    Write-Host "REHEARSAL PASSED: $database was clean-published, upgraded, and post-deployment verified. Preserve the generated logs as release evidence."
}
finally {
    if (-not $KeepDatabase) {
        # Only the GUID-named database generated by this process is eligible for cleanup.
        $sqlcmd = (Get-Command sqlcmd -ErrorAction SilentlyContinue).Source
        if ($sqlcmd) {
            & $sqlcmd -S $ServerInstance -d master -E -b -Q "ALTER DATABASE [$database] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$database];" | Out-Null
        }
    }
}
