/*
   One automatic fulfilment ticket may exist per order. Customer-created tickets
   remain untyped (0) and are never included in this invariant. Legacy rows are
   backfilled only when their item linkage and the former automatic opening text
   prove that they were generated by fulfilment; ambiguous historical tickets stay 0.
   Rollback: drop UX_Tickets_OneFulfillmentPerOrder and retain the additive column.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID(N'dbo.Tickets', N'U') IS NULL OR OBJECT_ID(N'dbo.OrderItems', N'U') IS NULL
    THROW 51700, 'Support fulfilment hardening requires dbo.Tickets and dbo.OrderItems.', 1;

IF COL_LENGTH(N'dbo.Tickets', N'IsFulfillmentTicket') IS NULL
    ALTER TABLE dbo.Tickets ADD IsFulfillmentTicket bit NOT NULL CONSTRAINT DF_Tickets_IsFulfillmentTicket DEFAULT (0);
GO

/* Conservative backfill: only old auto-ticket wording plus explicit SupportTicketId linkage. */
UPDATE t SET IsFulfillmentTicket = 1
FROM dbo.Tickets t
WHERE t.IsFulfillmentTicket = 0
  AND t.OrderId IS NOT NULL
  AND EXISTS (SELECT 1 FROM dbo.OrderItems oi WHERE oi.SupportTicketId = t.Id AND oi.DeliveryType = 3)
  AND EXISTS (SELECT 1 FROM dbo.TicketMessages tm WHERE tm.TicketId = t.Id AND tm.IsInternalNote = 0 AND tm.Message LIKE N'سفارش شما با موفقیت ثبت شد.%');
GO

IF EXISTS (SELECT 1 FROM dbo.Tickets WHERE IsFulfillmentTicket = 1 AND OrderId IS NOT NULL GROUP BY OrderId HAVING COUNT(*) > 1)
    THROW 51701, 'Multiple proven fulfilment tickets exist for one order and require manual reconciliation.', 1;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.Tickets') AND name = N'UX_Tickets_OneFulfillmentPerOrder')
    CREATE UNIQUE INDEX UX_Tickets_OneFulfillmentPerOrder ON dbo.Tickets(OrderId) WHERE IsFulfillmentTicket = 1 AND OrderId IS NOT NULL;
