<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>Vitorize.Api-ProductionReadiness</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vitorize.Application\Vitorize.Application.csproj" />
    <ProjectReference Include="..\Vitorize.Infrastructure\Vitorize.Infrastructure.csproj" />
    <ProjectReference Include="..\Vitorize.Shared\Vitorize.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Data\PrivateDocuments\01a6eb00e4f04a64ac919ca509080483\" />
    <Folder Include="App_Data\PrivateDocuments\033aaaf2da6a4975b83915b01983d901\" />
    <Folder Include="App_Data\PrivateDocuments\038e9f9dc52146e4a5a6e3977ea50981\" />
    <Folder Include="App_Data\PrivateDocuments\06633a77e3e04c499b96fd0e8c1bf913\" />
    <Folder Include="App_Data\PrivateDocuments\07d802a4b2ac48dcb7eb31b6cbf26912\" />
    <Folder Include="App_Data\PrivateDocuments\0b5d93c44c494349b89947c0448b08cb\" />
    <Folder Include="App_Data\PrivateDocuments\0b80a9842b9147368c87c968cdc98255\" />
    <Folder Include="App_Data\PrivateDocuments\0fa106621a334165857d484424b830d3\" />
    <Folder Include="App_Data\PrivateDocuments\113fb840e60846f5b0800351daf34acf\" />
    <Folder Include="App_Data\PrivateDocuments\1308efc9bc78438e9e499f5773ddb8de\" />
    <Folder Include="App_Data\PrivateDocuments\14667f04e81341e2b11539fb404d2b76\" />
    <Folder Include="App_Data\PrivateDocuments\14efba1fe0b64cc68fd5b59b46cfd9af\" />
    <Folder Include="App_Data\PrivateDocuments\16af39dbedea4370ac4b907a2af2a965\" />
    <Folder Include="App_Data\PrivateDocuments\19353012ca9b458182bd81aa518e53c2\" />
    <Folder Include="App_Data\PrivateDocuments\1971619b4e024b03ab5825f82e95792c\" />
    <Folder Include="App_Data\PrivateDocuments\224b2857ab4a4beb8414d2d33b05302a\" />
    <Folder Include="App_Data\PrivateDocuments\2919a788aaa0472c83086d1e11c7e0ae\" />
    <Folder Include="App_Data\PrivateDocuments\2b60e7eba0634d61bcf49b5ad15233ad\" />
    <Folder Include="App_Data\PrivateDocuments\2d47033eb6f34ebba0347ba6824ab802\" />
    <Folder Include="App_Data\PrivateDocuments\2dc5b04924a44c71b66fe48330ba52f6\" />
    <Folder Include="App_Data\PrivateDocuments\2f4c6b05d84c422c9bd73cd7d6ee7e14\" />
    <Folder Include="App_Data\PrivateDocuments\2fd7d7a5b8324dbcb1317d38bbdf3350\" />
    <Folder Include="App_Data\PrivateDocuments\312b5b3961bf4b609eb025b926409678\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000072\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000073\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000074\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000078\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000079\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000091\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000093\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000094\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000096\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000097\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000098\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000099\" />
    <Folder Include="App_Data\PrivateDocuments\33000000000000000000000000000100\" />
    <Folder Include="App_Data\PrivateDocuments\341c009b93584b9987a0d43447cdffea\" />
    <Folder Include="App_Data\PrivateDocuments\37883f9b805543d9958dcd55e05be520\" />
    <Folder Include="App_Data\PrivateDocuments\39ec8e8e6fae4825a09e94b5501b76e3\" />
    <Folder Include="App_Data\PrivateDocuments\3a826bab5aa24f65b0ad42ccb64c2848\" />
    <Folder Include="App_Data\PrivateDocuments\4738e3a6c2c24ae7a17ab79e258c00e6\" />
    <Folder Include="App_Data\PrivateDocuments\47a4434c68734df296b8347da38a8b97\" />
    <Folder Include="App_Data\PrivateDocuments\508992e90a2645e3a9fafedcefe1cb22\" />
    <Folder Include="App_Data\PrivateDocuments\532f626951e145e0b808ad38db436b48\" />
    <Folder Include="App_Data\PrivateDocuments\5914d55e71f142bcad1878a9be555d43\" />
    <Folder Include="App_Data\PrivateDocuments\5c11d4d3f5224eecabc6c6130069b935\" />
    <Folder Include="App_Data\PrivateDocuments\5e1effef4d4846feb7c5dbb6a967aea6\" />
    <Folder Include="App_Data\PrivateDocuments\6931d2b7924a4ef4a683af1fc16b5bd0\" />
    <Folder Include="App_Data\PrivateDocuments\6a25a840b42e4adabf037e6d9a9a7715\" />
    <Folder Include="App_Data\PrivateDocuments\6b2a442d76e54c8e8e54688ad9404df7\" />
    <Folder Include="App_Data\PrivateDocuments\6e43fee7857343a5bdf5706e4168798d\" />
    <Folder Include="App_Data\PrivateDocuments\7145291bce2a4122a144ecfa8632e813\" />
    <Folder Include="App_Data\PrivateDocuments\7513dded32224769be861b6dcefaedff\" />
    <Folder Include="App_Data\PrivateDocuments\78913bece9c24929951b3f91f7571d38\" />
    <Folder Include="App_Data\PrivateDocuments\79e739ec6a5b495792d5bacb483f4b3a\" />
    <Folder Include="App_Data\PrivateDocuments\7b4144631f82415ba396697a528d3318\" />
    <Folder Include="App_Data\PrivateDocuments\7b5528c93a494234bf26aedc7f0d6404\" />
    <Folder Include="App_Data\PrivateDocuments\80247cd8c2a246aa834c42463b568664\" />
    <Folder Include="App_Data\PrivateDocuments\807935b2601e43b1a7d2a4b9ea881e5a\" />
    <Folder Include="App_Data\PrivateDocuments\81987bfacf834b5eaaa7e9a811fc546d\" />
    <Folder Include="App_Data\PrivateDocuments\821be28ba94b4ccf9f4e6c7bc9e15b0b\" />
    <Folder Include="App_Data\PrivateDocuments\841cb9369bab4dcfa2b460fe59c959fb\" />
    <Folder Include="App_Data\PrivateDocuments\84c03000b2524109b5e285003e25c14d\" />
    <Folder Include="App_Data\PrivateDocuments\84d332eacf6b4063a19e826d0764ec0b\" />
    <Folder Include="App_Data\PrivateDocuments\8518cfe1207742b1814d173c02a81705\" />
    <Folder Include="App_Data\PrivateDocuments\8591f8d4afbb45a09f4715dd62197ac3\" />
    <Folder Include="App_Data\PrivateDocuments\860c3192c9cb403081964943b64ad9c1\" />
    <Folder Include="App_Data\PrivateDocuments\86b42a5f6e164cdbb18fc64bd342f40e\" />
    <Folder Include="App_Data\PrivateDocuments\91afc28a67c74d53a5a256595bf523e8\" />
    <Folder Include="App_Data\PrivateDocuments\91f8d5636a3f48549217c620ed4d6fd6\" />
    <Folder Include="App_Data\PrivateDocuments\9468394c62fb4f7894813a0953470a81\" />
    <Folder Include="App_Data\PrivateDocuments\95ff01666112425697befa53fd66741a\" />
    <Folder Include="App_Data\PrivateDocuments\962e4457183e45a0b7383963613ea5bf\" />
    <Folder Include="App_Data\PrivateDocuments\9913d44373eb4a5d9ba6f77cd5072deb\" />
    <Folder Include="App_Data\PrivateDocuments\9e9887a932f149f094e5172fa51b85aa\" />
    <Folder Include="App_Data\PrivateDocuments\9fc011184fe849deb172e866accd1113\" />
    <Folder Include="App_Data\PrivateDocuments\a1e109f64c2f41dba76df114237b6e9c\" />
    <Folder Include="App_Data\PrivateDocuments\a34f68ec5e544ba396f6df4a39b718ba\" />
    <Folder Include="App_Data\PrivateDocuments\a588b0d8b0594d999cb7465763718715\" />
    <Folder Include="App_Data\PrivateDocuments\a6659d8f9d0449d6980b8807ceb619b3\" />
    <Folder Include="App_Data\PrivateDocuments\a88881cdd68b4db684c9d8a13d86120f\" />
    <Folder Include="App_Data\PrivateDocuments\a90262b2856d4140a4671984838b5a9e\" />
    <Folder Include="App_Data\PrivateDocuments\a91f78c477d3411c8622107eaa541a0e\" />
    <Folder Include="App_Data\PrivateDocuments\a923996e26dd47abbc8ee1800740f7fb\" />
    <Folder Include="App_Data\PrivateDocuments\a97b530d0fcd46798e638defebe59055\" />
    <Folder Include="App_Data\PrivateDocuments\a9fcb2bc3a1b4b82b02da621c0929ec1\" />
    <Folder Include="App_Data\PrivateDocuments\aa2fb11c32b54297a9fa95774a88601a\" />
    <Folder Include="App_Data\PrivateDocuments\aa54b2d3651a42f88499c2cbfcadc389\" />
    <Folder Include="App_Data\PrivateDocuments\ab048a38644441c9ad079ce5b1d41369\" />
    <Folder Include="App_Data\PrivateDocuments\ab363541dd8241c188646adb296f432b\" />
    <Folder Include="App_Data\PrivateDocuments\ab4d8a93ef914eba8168ef7e4855dbab\" />
    <Folder Include="App_Data\PrivateDocuments\ae43bd6828424bc38d3aa364c1edd3d2\" />
    <Folder Include="App_Data\PrivateDocuments\ae62cac8b342467f802ff09dba3808aa\" />
    <Folder Include="App_Data\PrivateDocuments\afc63f07fccf4dd8a5aa0335e6374592\" />
    <Folder Include="App_Data\PrivateDocuments\b13ede87ab894a1e93cdf4dd5bb58081\" />
    <Folder Include="App_Data\PrivateDocuments\b4044eb1be994163ba291d4e049aa9b6\" />
    <Folder Include="App_Data\PrivateDocuments\b45d443f72564721bcbc7862c7bd872a\" />
    <Folder Include="App_Data\PrivateDocuments\b6b189dd91b144f393d74a614ebc4bcf\" />
    <Folder Include="App_Data\PrivateDocuments\c867de5e2ec54c918802f8c1eeb76b48\" />
    <Folder Include="App_Data\PrivateDocuments\c97f2195bc2c415083698ce9b57f8530\" />
    <Folder Include="App_Data\PrivateDocuments\ca97383daf4c468c9a087c1760fc5a3b\" />
    <Folder Include="App_Data\PrivateDocuments\cae9003408774678897fac9587198871\" />
    <Folder Include="App_Data\PrivateDocuments\caf8e926b9454950a9202aca0319f723\" />
    <Folder Include="App_Data\PrivateDocuments\ccf6b1d13a48487eb5f4a53c30022c78\" />
    <Folder Include="App_Data\PrivateDocuments\cf3ec1aaf09c4a818e7ba9ed7f293199\" />
    <Folder Include="App_Data\PrivateDocuments\d117f029379946bc9fd8e1cc08054e7b\" />
    <Folder Include="App_Data\PrivateDocuments\d12a928f7eaa40afb3709b3780666b0f\" />
    <Folder Include="App_Data\PrivateDocuments\d19a2ebaec824105a07c94d5f0040748\" />
    <Folder Include="App_Data\PrivateDocuments\d2d14c7653df479488c880f0d1358a01\" />
    <Folder Include="App_Data\PrivateDocuments\d6e5bdc6a5bf41d287321d7f732ddfc6\" />
    <Folder Include="App_Data\PrivateDocuments\d73fa654c1c44d11aa1cb0a69def5cc6\" />
    <Folder Include="App_Data\PrivateDocuments\db333a3edc11429e9cc018f335847da5\" />
    <Folder Include="App_Data\PrivateDocuments\df8233fecf0344edb1de0f88faf04e7a\" />
    <Folder Include="App_Data\PrivateDocuments\e0c358e460e94faf8a7277c4ce1406ba\" />
    <Folder Include="App_Data\PrivateDocuments\e5ae2c0d38cb4a2a9520c3e10b2a5dd2\" />
    <Folder Include="App_Data\PrivateDocuments\e6a253cba4144729af90d406bfef58e4\" />
    <Folder Include="App_Data\PrivateDocuments\e7276c83bd36462586269d477add5562\" />
    <Folder Include="App_Data\PrivateDocuments\efd869be4db741df99f8a59b2a7208f8\" />
    <Folder Include="App_Data\PrivateDocuments\f0b8260b28674779a4988c56090a7ad3\" />
    <Folder Include="App_Data\PrivateDocuments\fd7d4a9f8f3b435285e630f62b97c17a\" />
    <Folder Include="App_Data\PrivateDocuments\fdaf145dfe7f44599a5746f80b048954\" />
    <Folder Include="App_Data\PrivateDocuments\fde2090ec3684c7cac89b7265c27868b\" />
  </ItemGroup>

  <!-- Development and test configuration must never reach a published package: these files carry a
       JWT signing key, an encryption key and a local connection string, and a release is unpacked
       straight into the host's application directory. The host supplies appsettings.Production.json. -->
  <ItemGroup>
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
    <Content Update="appsettings.Testing.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
